# Generated by Django 4.1.3 on 2023-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='torrentList',
            field=models.JSONField(null=True),
        ),
    ]
