# Generated by Django 4.1.3 on 2023-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, choices=[('Delivery 1Q23', 'Delivery 1Q23'), ('2H Reflections', '2H Reflections'), ('Personal Todos', 'Personal Todos'), ('Staff Meetings', 'Staff Meetings'), ('WBA staff meetings', 'WBA staff meetings'), ('Iteration RPA', 'Iteration RPA'), ('Iteration WBA', 'Iteration WBA'), ('1on1 Fran', '1on1 Fran')], max_length=100),
        ),
    ]
