# Generated by Django 4.1.3 on 2023-03-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_torrentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='magnetlink',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
