# Generated by Django 4.1.3 on 2023-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_search_magnetlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropboxapitoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('appkey', models.CharField(blank=True, max_length=100)),
                ('oauth2refreshtoken', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
