# Generated by Django 4.1.3 on 2023-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_expense_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Quarter',
            field=models.CharField(choices=[('1Q', '1Q'), ('2Q', '2Q'), ('3Q', '3Q'), ('4Q', '4Q')], max_length=2),
        ),
    ]
