# Generated by Django 4.1.3 on 2023-03-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_expense_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
