# Generated by Django 4.1.3 on 2023-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_expense_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='quarter',
            field=models.CharField(max_length=2),
        ),
    ]
