# Generated by Django 4.1.3 on 2023-03-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_expense_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='qBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=2)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('tc', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
