# Generated by Django 4.1.3 on 2023-03-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_qbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rendido',
            field=models.BooleanField(default=False),
        ),
    ]
