# Generated by Django 3.2.7 on 2021-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_award_totalamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200)),
                ('bot_nbr', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('autotype', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200)),
                ('bot_nbr', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('autotype', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
