# Generated by Django 4.1.3 on 2023-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quarter', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
