# Generated by Django 4.1.3 on 2023-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateField(),
        ),
    ]
