# Generated by Django 4.1.3 on 2023-03-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expense_quarter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Quarter',
            new_name='quarter',
        ),
    ]
