# Generated by Django 4.1.3 on 2023-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_description_expense_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
