# Generated by Django 4.1.3 on 2023-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_expense_rendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
