# Generated by Django 4.2.7 on 2023-12-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_expense_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='qbudget',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='qbudget',
            name='tc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
