# Generated by Django 4.2.7 on 2024-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_expense_monto_alter_qbudget_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
