# Generated by Django 4.2.7 on 2024-09-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_expense_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
