# Generated by Django 4.1.3 on 2023-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, default=['Delivery 1Q23', '2H Reflections', 'Personal Todos', 'Staff Meetings', 'Iteration RPA', 'Iteration WBA', '1on1 Fran'], max_length=100),
        ),
    ]
