# Generated by Django 4.1.3 on 2023-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_award_who'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='monto_bp',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='award',
            name='monto_cash',
        ),
        migrations.AddField(
            model_name='award',
            name='bp',
            field=models.BooleanField(default=False),
        ),
    ]
