# Generated by Django 4.2.7 on 2024-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_monto_bp_award_monto_remove_award_monto_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
