# Generated by Django 3.2.7 on 2021-09-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_metricpivot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricpivot',
            name='tot_bots',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
