# Generated by Django 3.2.7 on 2021-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_alter_metricpivot_tot_bots'),
    ]

    operations = [
        migrations.CreateModel(
            name='backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200)),
                ('bot_nbr', models.CharField(blank=True, max_length=200)),
                ('autotype', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
