# Generated by Django 3.2.7 on 2021-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
