# Generated by Django 3.2.7 on 2021-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_backlog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, max_length=200)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('goalamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('wizardamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
