# Generated by Django 3.2.7 on 2021-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
