# Generated by Django 3.2.7 on 2021-11-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_specification_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='dsl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='validation',
            name='dsl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
