# Generated by Django 4.1.3 on 2023-08-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pmr',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
