# Generated by Django 4.1.3 on 2023-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_title_award_award_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='who',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
