# Generated by Django 4.1.3 on 2023-08-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='votacion',
            new_name='votados',
        ),
    ]
