# Generated by Django 4.1.3 on 2023-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0005_delete_nominados'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='ganador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
